[project]
name = "pj-py"                          # <-- EDIT THIS per project
dynamic = ["version"]
description = "Spawn Python projects from templates."
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.10"
dependencies = []

[tool.hatch.version]
path = "src/pj_py/__init__.py"

[project.scripts]
pj-py = "pj_py:main"               # <-- EDIT THIS per project

[dependency-groups]
dev = [
    "pytest>=9.0",
    "ruff>=0.15",
    "fastship",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 160
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[tool.fastship]
branch = "main"
